# Generated by Django 4.2.6 on 2023-11-08 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("marca", models.CharField(max_length=100)),
                ("ano", models.IntegerField(default=0)),
                ("imagem", models.CharField(max_length=255)),
                ("quantidade", models.IntegerField(default=0)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Aluguel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.carro"
                    ),
                ),
            ],
        ),
    ]
